import "@/styles/globals.css";
import Link from "next/link";
import SearchBar from "./(main)/components/SearchBar";
import ButtonGroup from "@/components/ButtonGroup";
import logo from "@/public/assets/svg/logo.svg";
import Image from "next/image";
import { ToastContainer } from "react-toastify";
import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";

import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "MeCredit",
  description: "Generated by Next.js",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <SessionProvider session={session}>
          <div>
            <header className="fixed top-0 h-16 w-full bg-white">
              <div className="flex h-full w-full items-center justify-evenly">
                <Link href="/">
                  <Image src={logo} alt="logo" />
                </Link>

                <SearchBar />
                <ButtonGroup />
              </div>
            </header>

            <section className="mx-auto mt-[80px] h-[calc(100dvh-80px)] max-w-screen-sm">
              {children}
              <ToastContainer />
            </section>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
